### ISSUE TITLE
Feature Request: Blog in multiple languages

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#177]
Similar to qtranslate for Wordpress:

in the markdown files (either static page or blogpost-entry) there could be added a feature for comments like this:
`<!--::lang_de::  hier kommt der deutsche Text   ::lang_de::-->`
`<!--::lang_en::  Here comes the english text   ::lang_en::-->`
`<!--::lang_fr::  Ici est le text en français   ::lang_fr::-->`
`<!--::lang_it::  'similar on italian'   ::lang_it::-->`

then in the config file one should be able to set the default language: e.g. **en**
and also in the config file there could be a value set of available languages: e.g. `en,de,fr,it` or `en->English,de->Deutsh,fr->Français,it->Italiano`

then in the column next to the main content OR in the menu bar, the site visitor shoul be able to choose the language of the content. If there is no content available for that specific language, the content for the default language should be displayed - but if in a md-file there are no language-tags (like in the example above) then it should be just assumed, that the following content is in the default language.

I hope you get my idea...

**Comment by danpros** [comment]
Perhaps we just need to fix the remove_accent function so it will strip the character properly

**Comment by Silverunit** [comment]
Hi, Nice update the last one!
In this matter, would it be possible to add the "tags" in a similar way. Or even in a .md kind of way to add tags to your posts? If so I could help with translating HTMLy to Swedish if you are interested.

Our site are online now www.silverunitsystems.se/nyheter/ were "nyheter" is runing HTMLy and the rest is hardcoded html.

Best regards, Michael

**Comment by danpros** [comment]
@Silverunit with those update now htmly become more open for any modifications via template, you can list any content using get_posts, list based on tag using get_tag etc.

That's nice blog :smile: will add it on showcase :smile:

**Comment by Silverunit** [comment]
Hey thanks!
If you find a way to store it, then åäö should be possible to add in the same way the headlines are stored and decoded today I think. In the future we will be add more languages to the site. As we did back when we had wordpress as platform. So this multiple language is of our interest. With this solution we are in more control then wp. And also it loads faster.

And if you add  the "locale" to the php (in main layout I think) and config, then it will be possible to have the post date showing up in your language of choice e.g. en_US as config. But it only works if the host has locale active in the php version. Been trying to add it manually but it turns out our host does not have that active.

**Comment by danpros** [comment]
@Silverunit 

Seems I got the way how to achieve that without performance issue (tag cloud). Perhaps you realized if htmly using very small memory footprint because htmly searching the post tags, date, archive etc. by examine the file name and not open it.

So for tags let say I am creating tags.lang file. We creating the post with tag `Örebro` and when we save this, there are two string `Örebro` and `Orebro`. and we save it as an array:

````
Array
(
    [Orebro] => Örebro
)
````

Later if we request Orebro than we give it Örebro as the display. Orebro as clean URL. 

For individual post than we can use the title method.

**Comment by danpros** [comment]
Please test the latest master branch. I already commit some improvements.

**Comment by gesundelehre** [comment]
I'm sorry, but I don't understand how to use this function - of I don't even understand what you mean with the **tags.lang** file and what this would be userful for...

**Comment by danpros** [comment]
@gesundelehre no need to use that function. Please try the latest master branch than creating tag using non latin char, it should work now. Than please search those tag as well using the search form.

**Comment by Silverunit** [comment]
Hi @danpros, been working in Finland. I will start testing this weekend. Sounds like a good way to do it.

**Comment by danpros** [comment]
@Silverunit just releasing new version contains this feature.

I am creating `tags.lang` inside content folder than save the tags there. And this file is important like views.json :smile:

**Comment by markosu** [comment]
Please, add dateformat to config.

**Comment by danpros** [comment]
@markosu you can change it by modify directly the main.html.php and post.html.php

````
<?php echo date('d F Y', $p->date) ?>
````

**Comment by danpros** [comment]
We should merger language discussion into this #134
