### ISSUE TITLE
Posting from shel

### ISSUE THREAD

**Issue by monasor28** [danpros/htmly#186]
Hey thanks for this. !

I would like to know how to post from the shell. Like grav and pico can? Is there any doc on themes.

**Comment by danpros** [comment]
Well see file naming conventions https://github.com/danpros/htmly#file-naming-convention.

Doc on themes? currently nope but you can read it here using chrome browser http://t3n.de/news/htmly-schlankes-blog-system-ohne-datenbank-532731/ very simple actually. But that is old write up but similar with current state. The `blog theme` is a little bit custom (to modify the output) so use the `logs theme`.

Example from logs theme to display the recent posts:
````
<div class="recent">
   <h3>Recent Posts</h3>
    <?php echo recent_posts() ?>
</div>
````
That will render as a list.

 And from the blog theme become like this since I want to make a custom layout and not just a list.
````
<div role="tabpanel" class="tab-pane active" id="recent-posts">
	<h2 class="hide">Recent Posts</h2>
	<?php $lists = recent_posts(true);?>
	<?php $char = 60;?>
	<?php foreach ($lists as $l):?>
		<?php if (strlen(strip_tags($l->title)) > $char) { $recentTitle = shorten($l->title, $char) . '...';} else {$recentTitle = $l->title;}?>
		<div class="item">
			<h3 class="title"><a href="<?php echo $l->url;?>"><?php echo $recentTitle;?></a></h3>
			<div class="content">
			<p><?php echo shorten($l->body, 75); ?>...</p>
			<a class="more-link" href="<?php echo $l->url;?>"><i class="fa fa-link"></i> Read more</a>
			</div><!--//content-->
		</div>
	<?php endforeach;?>
</div>
````

The `recent_posts(true);` mean return as an array.

**Comment by love-decay** [comment]
I love it ....

**Comment by love-decay** [comment]
Where do I find the API ?

I am trying to make posts from the shell. Look here http://learn.getgrav.org/content/headers

**Comment by danpros** [comment]
The date, the slug is in filename and not inside the file.

htmly is different with almost flat file cms out there.

**Comment by love-decay** [comment]
i understand but how can i build a post only from CLI/shell.

I can see post and pages have 
<--t -->
<--d -->

**Comment by danpros** [comment]
Explanations:
````
<!--t The title t-->
<!--d The descriptions d-->
<!--tag this useful when using non latin char t-->
<!--image the featured post image url image-->
<!--video the featured youtube video url video-->
 etc....
````
All optional except the title. And is some cases the title is empty than htmly use "Untitled - post creation time " as title.

**Comment by love-decay** [comment]
thank you

**Comment by danpros** [comment]
Hello, I will close this one. Thanks,
