### ISSUE TITLE
Config issue ( I think/hope)

### ISSUE THREAD

**Issue by Snip1** [danpros/htmly#273]
Just started playing with HTMLy... thanks so much for putting an _actually_ basic flatfile markdown system out there, Danpros.  You really should be taking over the world with this thing...

You are right, btw: the docs need work ;)

On that: I am integrating the blog into an existing website, retaining the look of the existing site.  Going fairly well.  I'm doing the work with Coda/MAMP Pro on a local dev server, and am running into some strange behaviours as regards url resolution, to the degree that it often breaks functionality either on the 'public' or 'admin' side, and sometimes both.

I suspect the issue has to do with the config setting in config.ini.  I am using either:

`; The URL of your blog. Include the http or https if you are using Facebook or Disqus comment. 
site.url = "http://h2onlyserve:8888/blogg/index.php"` 

or

`; The URL of your blog. Include the http or https if you are using Facebook or Disqus comment. 
site.url = "http://h2onlyserve:8888/blogg/"`

The first seems to break admin, and the second the public.  Any ideas?  Getting 404's and/or strange display issues (css not loading?)... there might even be cache issues involved tho I am trying to keep the caches clear on both the HTMLy sol and the browser.

**Comment by danpros** [comment]
> You really should be taking over the world with this thing...

Well this is too much :smile: 

How about the error log?

**Comment by Snip1** [comment]
Actually, I did I bit more digging (I really was suspicious of cache issues, as you read above) and found the cache switch in the .ini file.  All better, it would seem.

I imagine I'll run into other roadblocks or speed-bumps along the way, but right now this is excellent. Looking forward to going beta with it ;)

This really is a sweet little sol, Dan.  Why is it *not* killing it out there?  I've been looking on and off for this for more than a year (kicked Grav to the curb earlier this week... ("No, I *don't* want to learn Twig and SASS, thank you very much!")... what you have on offer is, as near as I can tell (not that that says a helluva lot), pretty unique and clean.

**Comment by danpros** [comment]
@Snip1 well I take performance as my first priority. You can test its performance also. Try 10k or 50k blog posts and turn on the page generation time :smile: 

If not using any widget on the sidebar (menus etc.) with 9k+ posts with per pager 5 posts the page generation time is around 0.0005 seconds (test it on 1GB RAM VPS, 2 x CPU 2.2GHz, SSD). The only widget that need to improve is the auto generated menu, if it contains too many static page it will slow down a bit, it should fixed in next version by caching the resulting array (current solutions is using custom menu or hardcoded the menu to the template it self).

Test blog on free OpenShift: http://goo.gl/LZj7w0

I am very glad if anyone would like to participate in developing it.
