### ISSUE TITLE
Unable to create new posts from Admin

### ISSUE THREAD

**Issue by dixonge** [danpros/htmly#332]
I can create new pages, but the links for all post types do nothing. No errors, just no response at all.

**Comment by howlerwolf1313** [comment]
I'm having this same issue.

**Comment by howlerwolf1313** [comment]
I get the following error from nginx log:

2018/12/10 15:10:55 [error] 1312#1312: *25 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: type in /var/www/html/removed/blog/system/htmly.php on line 397" while reading response header from upstream, client: 192.168.13.1, server: removed.com, request: "GET /blog/add/content?type=post HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "removed.com", referrer: "https://removed/blog/admin/content"

**Comment by ncang** [comment]
Make sure your domain, ip is correct,,, check config.ini
This is local environments?


On Dec 11, 2018 6:15 AM, "howlerwolf1313" <notifications@github.com> wrote:

I get the following error from nginx log:

2018/12/10 15:10:55 [error] 1312#1312: *25 FastCGI sent in stderr: "PHP
message: PHP Notice: Undefined index: type in
/var/www/html/removed/blog/system/htmly.php on line 397" while reading
response header from upstream, client: 192.168.13.1, server: removed.com,
request: "GET /blog/add/content?type=post HTTP/2.0", upstream:
"fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "removed.com", referrer: "
https://removed/blog/admin/content"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danpros/htmly/issues/332#issuecomment-446010990>, or mute
the thread

**Comment by howlerwolf1313** [comment]
Domain is correct in config.ini. 

site.url = "https://1manwolfpak.com/blog"

corresponds to a /blog folder in root

**Comment by howlerwolf1313** [comment]
I can create a static page but nothing else. This is yourls in a docker container.

**Comment by danpros** [comment]
@howlerwolf1313 seems related to: https://docs.htmly.com/web-servers/nginx

**Comment by dixonge** [comment]
This should have been closed years ago...
