### ISSUE TITLE
www.htmly.com not working?

### ISSUE THREAD

**Issue by pitamatein** [danpros/htmly#362]
Ouch, looks like this project has been abandoned. Shame, as it has real value IMO.
Needed to access the www.htmly.com website because I think that's where docs on the config keys were documented. 

For example what do the following mean, and what is the syntax?

* blog.menu 
* breadcrumb.home

**Comment by m45rud** [comment]
IMHO, HTMLy is still maintained by developers though with little concern as no bugs are found.

HTMLy is a side project of @danpros, but due to busyness in other business so he can't manage this project properly. Therefore, he invited anyone who wants to be the co-maintainer of this HTMLy project. You can see [this](https://github.com/danpros/htmly/issues/358).

Config key just a variable that store some value that can print out the value anywhere in your template, for example `blog.menu`.
