### ISSUE TITLE
CVE-2019-8349 XSS vulnerabilities in 2.7.4

### ISSUE THREAD

**Issue by fgeek** [danpros/htmly#390]
Advisory: https://www.netsparker.com/web-applications-advisories/ns-18-059-cross-site-scripting-in-htmly/

Status says not fixed. What is the status now or plans to fix this.

**Comment by bluebirch** [comment]
It has not been fixed, the source has not been touched for a long time. What would be needed to fix this? Is anyone around here knowledgeable enough to deal with this? (I'm beginning to consider help maintaining HTMLy, but lack the necessary PHP skills.)

**Comment by medmen** [comment]
indeed, it looks like the source is abandoned. Maybe someone can reerect the project, i am willing to help fix and imrove.
In this case, the view components of htmly dont sanitize GET / POST data before displaying them, thereby opening a XSS-door (like cookie-stealing).

To prevent this, all GET and POST data has to be sanitized, libraries for stuff like that exist (like HTMLpurifier). 
So in the first example the view-file "system/admin/views/delete-page.html.php" could contain something like
`    if (isset($_GET['destination'])) {
        $config = HTMLPurifier_Config::createDefault();
        $purifier = new HTMLPurifier($config);
        $destination = $purifier->purify($_GET['destination']);
    }
` 
 
But since this behaviour affects all views in general it should IMHO idealy be targeted by a function available to all views, so you could simply do something like 
`if (isset($_GET['foo'])) {
    $foo = sanitize($_GET['foo']);
}`
whenever necesary.

**Comment by bluebirch** [comment]
I have offered trying to maintain the project (see #358). Although my knowledge of PHP is sparse, I think I can deal with GitHub.

**Comment by danpros** [comment]
This has been fixed. Please review it: https://github.com/danpros/htmly/commit/ec1cf1d303598679536ec0934190e0d63731c4e6

**Comment by danpros** [comment]
Just releasing new version with this fixes.
