### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by ghost** [danpros/htmly#44]
Do you have it in plans? Calendar, agenda view, anounce...

**Comment by Xarcell** [comment]
I would like to see a event calendar as well. My clients don't like having to use a separate system(google calendar) for creating events and I don't have any alternative solutions.

**Comment by Xarcell** [comment]
I had a thought. Perhaps a widget that shows only a list of posts by date where the "event" tag was used? Would be nice if it showed a monthly calendar with it too though.

On my clients websites I have to call two google calendars with different view settings. One set to monthly view, and the other set to list view; just to get the desired effect. However, my clients keep calling me asking me to add events because they always mess it up. They either add a date to the wrong calendar(personal by default), don't understand how to use google calendar, or refuse to sign up with google over privacy issues. The list of excuses go on and on...

Here is a screenshot of the two calendars in a custom HTML gadget on Blogger:
![screenshot-calendar-widget](https://cloud.githubusercontent.com/assets/6114450/9761930/e18e96e8-56cd-11e5-82e5-8742c7bc9468.png)

If we could something at least close to this I would appreciate it. 

Calendar events is a make or break for my clients, and they currently hate how I've done it. The only choice is to move to another web application and make them pay for web hosting. This is difficult, because I'm trying to keep them off of SQL servers(because SQL servers in shared hosting isn't reliable to oblivious users). Thus, noDB or SQLite web applications are my only options that I want to offer to my clients.

**Comment by danpros** [comment]
@Xarcell so you want to display let say specific tags? there is a built in function for that, yes undocumented yet. I will open the Wiki and make any body can edit it so other user can add any tips.

Let say you want to display the "event" tag, just use the get_tag() function:

````
function get_tag($tag, $page, $perpage, $random)
````
Example:
````
$events = get_tag('event', 1, 5, false);
foreach ($events as $e) {
    echo '<div>' . $e->title . '</div>';
}
````
Or get the category event:

````
function get_category($category, $page, $perpage)
````

Example:
````
$events = get_category('event', 1, 5);
foreach ($events as $e) {
    echo '<div>' . $e->title . '</div>';
}
````

**Comment by Xarcell** [comment]
Thank you for this.
