### ISSUE TITLE
Video posts broken since update?

### ISSUE THREAD

**Issue by StarRico** [danpros/htmly#482]
Hi, All Youtube video posts across our site are now reporting errors since updating. The error shows as follows:

An error occurred. Please try again later. (Playback ID: 89Fox9d8oxZ9VP06)

**Comment by danpros** [comment]
Hello,

Seems because of the theme, please download the new theme.

If you are not using theme shipped with HTMLy source code, please download the updated version. If you already modify the theme and don't want your changes to be lost, simply update the `<?php echo $p->video;?>` to `<?php echo get_video_id($p->video); ?>` in main.html.php and post.html.php.
