### ISSUE TITLE
Losing my edits

### ISSUE THREAD

**Issue by CharliePoole** [danpros/htmly#535]
I'm running HTMLy with the blog theme. A couple of times, I was interrupted while I was editing a page and came back to continue after a delay. When I went to save my changes, I was asked for my login credentials. After I logged in, my changes were gone. This seems like a bug... As a workaround, is there any way to tell the editor to automatically save the draft as I work?

**Comment by dirmanhana** [comment]
sounds good if there is an auto draft feature

**Comment by rolandixor** [comment]
I'm not sure if this was ever addressed, but I'm having the same issue. Losing work because drafts aren't being saved automatically.

**Comment by KuJoe** [comment]
Currently working on an auto save to drafts feature, should be ready by this weekend.
https://github.com/danpros/htmly/issues/722#issuecomment-2118388046

**Comment by CharliePoole** [comment]
That would be a welcome addition, IMO.

**Comment by KuJoe** [comment]
I've made it a little cleaner and I got it working for all forms of posts. There are some minor bugs I need to work our such as creating multiple drafts if you change your tags/titles so I may put some intelligence behind it so it doesn't start to auto save until you've started writing in the content field.

It also does not work on edits of existing posts/drafts, it only works for new posts. This might be a bigger discussion though because I personally don't want to overwrite existing drafts if I'm working on edits I might not keep.

![image](https://github.com/danpros/htmly/assets/1040086/1ea98b4c-c92f-4139-99d2-d3dec44241be)

**Comment by danpros** [comment]
> It also does not work on edits of existing posts/drafts

Yes, autosave should only in draft.

**Comment by KuJoe** [comment]
This can probably be closed due to PR #757

**Comment by danpros** [comment]
Thanks
