### ISSUE TITLE
HTMLy with Reseller Hosting 

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#583]
Any suggestions on using HTMLy as my sales page for my reseller hosting business? Just getting started with the hosting business but I love HTMLy.

Rick

**Comment by JPLeRouzic** [comment]
No need to modify HTMLy, I guess a simple solution would be to use Apache's (or similar HTTP servers) virtual server facility.
This way you need only one VPS, and there are tools to manage virtual servers.
https://github.com/search?q=apache+virtual+management
I use Apache's virtual servers since 15 years and it works well.

**Comment by AutomationMan808** [comment]
Thank you for that. I'm actually renting a server utilizing their reseller hosting program.

Rick
