### ISSUE TITLE
CSRF Token not correct

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#590]
Grrr cleared the cache

added

<code>
<IfModule mod_php5.c>
    #Session timeout
    php_value session.cookie_lifetime 1200
    php_value session.gc_maxlifetime 1200
</IfModule>

<IfModule mod_php7.c>
    #Session timeout
    php_value session.cookie_lifetime 1200
    php_value session.gc_maxlifetime 1200
</IfModule>
</code>
To .htaccess

Still having this problem

**Comment by JPLeRouzic** [comment]
You should have used [the issue already open on that topic.](https://github.com/danpros/htmly/issues/572)

And you give no information about your HTTP host, and your host provider.

I did a lot of checks on the other issue which was about Lima host provider.

My conclusion is that there are issues on several points:
- HTMLy [had recently changed its cookie management,](https://github.com/danpros/htmly/commit/0bc0931eff75773b15ae95133f31b523aae47313) now it supports only Apache's cookies $_COOKIE['PHPSESSID'] . This looks to be **a weird choice**.
- Some host providers such as Lima claim they offer Apache HTTP hosting, yet they set only Nginx cookies which are incompatible today with HTMLy. It's possible to tweak HTMLy to make it compatible with Lima hosting, yet the whole login procedure on HTMLy looks very convoluted and in my opinion should be rewritten entirely. HTMLy is 9 years old and based on a framework (dispatch) which is even older, and the accumulated tweaks on the code base during those 9 years are not for the best. 

- Can you check with this version of HTMLy (2.8), I have too much work to do it myself.
On my website, I used initially 2.7 version that I had tweaked enormously since.  Version 2.8 added several languages. Yet it means that you will not being able to update HTMLy or it will reintroduce the Apache only cookie management.

**Comment by danpros** [comment]
Please see #572

Thanks,
