### ISSUE TITLE
Scheduled publishing

### ISSUE THREAD

**Issue by ctuxboy** [danpros/htmly#592]
Started a blog with htmly (it's a work in progress), so i want to publish blog post scheduled.
But when making a blogpost with a date in the future, then it shows directly.
- Is this a bug in htmly?
- Or someone knows how develop this?
- Or can this option added to htmly in a next version?

**Comment by bttrx** [comment]
You may call this a bug, but I think, HTMLy allows changing the date for past articles, i.e., scheduling in advance is impossible.

**Comment by ctuxboy** [comment]
> You may call this a bug, but I think, HTMLy allows changing the date for past articles, i.e., scheduling in advance is impossible.

Again, thanks for your answer @bttrx

**Comment by JPLeRouzic** [comment]
Won't it possible to :
- add a intended publication date in post's markdown at creation time in function add_content and, 
- make a test for the current date versus the intended date in function get_posts() before displaying posts?
A bit similar mechanism is already in place in "recent posts" which indexes recent posts in "cache/widget/recent.cache".
Instead of writing in recent.cache, all is needed is putting the intended publishing date in the post in markdown.

**Comment by ctuxboy** [comment]
> Won't it possible to :
> 
> * add a intended publication date in post's markdown at creation time in function add_content and,
> * make a test for the current date versus the intended date in function get_posts() before displaying posts?
>   A bit similar mechanism is already in place in "recent posts" which indexes recent posts in "cache/widget/recent.cache".
>   Instead of writing in recent.cache, all is needed is putting the intended publishing date in the post in markdown.

That's useful info.
Okay, i will try this soon, when working on the template-files.
At the moment i made my posts in draft, and manually make it public at some times.
