### ISSUE TITLE
When viewing site on a phone browser the static pages do not display or refresh correctly

### ISSUE THREAD

**Issue by MrBear777** [danpros/htmly#605]
Static pages do not show next to the Home selection when running on a phone browser. When you view a post then the static page link will show. But will not be displayed when going back to the homepage. This was working on another theme but not this one. I took a quick look at the code but I do not claim to any expert in PHP coding but can figure out the simple stuff. This issue is above my pay grade. Otherwise the theme works great.

**Comment by JPLeRouzic** [comment]
Can you provide a URL with this problem?

**Comment by MrBear777** [comment]
The issue look like it was resolved after the cache was cleared

**Comment by JPLeRouzic** [comment]
Even if it's advertised as a cache it is actually just using a copy of various indexes.
A real cache is something entirely different.
actually I think that in HTMLY this pseudo cache slows the site, as each time a post is displayed to a user, there is a read of the whole flat file database (with a PHP glob which is a slow function).
![image](https://user-images.githubusercontent.com/18621529/215283449-ddd8afca-cf0c-4d35-a080-35942f9f847c.png)

In my own version of HTMLy, I removed this "cache" code.

**Comment by AutomationMan808** [comment]
In which file is that?

**Comment by danpros** [comment]
This cache index only changed/rebuilt when we publish/edit/delete the post/page/category, or clear the cache manually. So we do not need the do the glob everytime actually `if (!file_exists($url))`

```
        $url = 'cache/index/index-sorted.txt';
        if (!file_exists($url)) {
            rebuilt_cache('all');
        }
```

For OP problems because on mobile you get the cached version (not logged) and let say on laptop logged so get un-cached version. If you still developing the site, turn off the cache in admin/config
