### ISSUE TITLE
Does the No Cache button work or should I delete some lines of code?

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#615]
I'm going to experiment with adding automated content. The last time I did that I left the cache on and had to remove it with an FTP program it got so huge. 

If anyone has any advice on adding automated content let me know. I plan on using RSS feeds from newsfeeds.

Rick

**Comment by JPLeRouzic** [comment]
I do it since a year or so, yet after the initial enthusiasm I made  a few changes:
As there is no CRON on HTMLy you have to use some programmatic hook to create the new posts.
Yet if you create only temporary content, search engines would complain that posts have disappeared.
If you just copy content from other web sites search engines will downgrade your rank (and it's enough bad as it is).

I don't want to create any content automatically so there should be a way to create only post that have value for the user and improve it later.

My idea was to put some social button on temporary content and when a user would click it, it would create a post. It would be implemented as usual. To me it looked reasonable, it would be a sign the post would be interested so it would make sense to make it permanent and then I could improve this post and search engines would be happy.
The problem is the search engines. 
They "click" on whatever they find and memorize it, so:
- They create multiple instances of your post
- Long after the temporary content has disappeared, the search engines are still "clicking" on a link that do not exist anymore. 
So after that I made clicks to create draft posts only, yet it is still a burden.

**Comment by AutomationMan808** [comment]
It won't be temporary content.
