### ISSUE TITLE
online-installer redirects to non existing pages

### ISSUE THREAD

**Issue by richardklingler** [danpros/htmly#621]
Uploaded online-installer.php to my Debian apache2 webroot and fired it up in web browser...

After few seconds it redirects me to the URI

/add/content?type=post

which doesn't exists and a 404 page is shown...

The base URL is visible, but when clicking on "Admin", it doesn't exist as well.

The directory layout is after calling the online isntaller (which is the same as for the local installer script):

```
drwxr-xr-x 4 www-data www-data  4096 31. Mai 09:09 cache
-rw-r--r-- 1 www-data www-data   507 31. Mai 09:08 composer.json
-rw-r--r-- 1 www-data www-data  9019 31. Mai 09:08 composer.lock
drwxr-xr-x 3 www-data www-data  4096 31. Mai 09:08 config
drwxr-xr-x 3 www-data www-data  4096 31. Mai 09:08 content
-rw-r--r-- 1 www-data www-data  2082 31. Mai 09:08 COPYRIGHT.txt
-rw-r--r-- 1 www-data www-data  1150 31. Mai 09:08 favicon.ico
-rw-r--r-- 1 www-data www-data   301 31. Mai 09:08 humans.txt
-rw-r--r-- 1 www-data www-data   130 31. Mai 09:08 index.php
drwxr-xr-x 2 www-data www-data  4096 31. Mai 09:08 lang
-rw-r--r-- 1 www-data www-data 18092 31. Mai 09:08 LICENSE.txt
-rw-r--r-- 1 www-data www-data  8504 31. Mai 09:08 README.md
-rw-r--r-- 1 www-data www-data  1154 31. Mai 09:08 robots.txt
drwxr-xr-x 8 www-data www-data  4096 31. Mai 09:08 system
drwxr-xr-x 8 www-data www-data  4096 31. Mai 09:08 themes
-rw-r--r-- 1 www-data www-data  1631 31. Mai 09:08 upload.php

```

**Comment by JPLeRouzic** [comment]
As I am a user of a much modified, older code base, I didn't know anything about "online-installer.php", so I had a look.
It seems its primary purpose is to install a lot of certificates on the server, which looks to me to be a very strange insecure behavior.

Anyway as HTMLy is only updated infrequently since 2017, it will be made unusable as PHP versions progress.

**Comment by tikita** [comment]
Does HTMLy works with PHP 8.1?

After installation (with the online-installer.php) is displayed:

_Internal Server Error_

_The server encountered an internal error or misconfiguration and was unable to complete your request._

_Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error._

_More information about this error may be available in the server error log._

_Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request._

**Comment by JPLeRouzic** [comment]
* HTMLy must be upgraded to PHP 8.2 (now the official version).
* Internal server error is very generic, please enable error logging on the browser (at least by inserting the two following lines in index.php and /system/htmly.php)
* Everybody should understand that HTMLy is primarily not maintained since 2017 with a small activity before 2022 ... which introduced several bugs.
* Everybody should know that HTMLy is a large hack on light frameworks that are not maintained for 10 years.
* There are many other flat file blogs, including blogs using sqlite (and PDO).
PHP has support for SQLite since many years. This removes the need for a MySQL/MariaDB database.

**Comment by JPLeRouzic** [comment]
Some people might be interested by this:
https://blogiestools.com/wordpress-sqlite-database/

**Comment by danpros** [comment]
Please make sure the mod_rewrite is installed. 

@tikita the latest version support up to PHP 8.3.
