### ISSUE TITLE
Is this project abandoned or unmaintained ?

### ISSUE THREAD

**Issue by lexavey** [danpros/htmly#629]
I want give some help updating system text editor to better version.

**Comment by oleteacher** [comment]
Yes, it does seem that way. Very sad because we have used it in classroom for a few years as student blogs. We were informed last week that if no updated to get PHP 8.2 ready, HTMLy was getting kicked off school networks on Dec 2023.

Sad day in HTMLy world :(

**Comment by JPLeRouzic** [comment]
DanPros has not published anything since 2015 (8 years ago) except one **_buggy_** commit in 2021.

**Comment by oleteacher** [comment]
@JPLeRouzic You got me all excited again:) Then I find your project is dead.

**Comment by JPLeRouzic** [comment]
Nobody has shown any interest so I archived it. I guess it's possible to de-archive it.

**Comment by JPLeRouzic** [comment]
It's again possible to make push requests on (https://github.com/JPLeRouzic/Coralie)

**Comment by oleteacher** [comment]
I will pass the info on to someone higher than my pay grade. The IT department:) Simple school teacher that must reply on others to approve usage on school network.

Thank you @JPLeRouzic

**Comment by lexavey** [comment]
> DanPros has not published anything since 2015 (8 years ago) except one **_buggy_** commit in 2021.
> 
> I made an update to PHP 8.1 (without internationalization):
> 
> https://github.com/JPLeRouzic/Coralie

I will try this "modded" htmly version, i love htmly because simple to use, no need setup database, customizable. 
backup and restore is as easy as moving files.

**Comment by AutomationMan808** [comment]
> Nobody has shown any interest so I archived it. I guess it's possible to de-archive it.

I'd love it was backwards compatible with PHP 7.*

**Comment by JPLeRouzic** [comment]
Hi,
I don't intent to support users, they have too diverse queries and so different infrastructures.
Coralie is just to show what HTMLy could become: A much more modular, easy to debug, compatible with modern PHP, tested with PHPStan (static analysis because there are hundred of bugs in HTMLy).
@AutomationMan808 if your host don't support PHP 8, move to another provider. Not supporting PHP 8 is a sign of very bad quality.
To test Coralie I use [Lima City](https://www.lima-city.de) free offer. They are a very good, friendly provider.
Making HTMLy compatible with PHP 8.2 is a matter of just a few days of work.

**Comment by bttrx** [comment]
Totally unexpected to me, but HTMLy version 2.8.4 has been released 3 days ago: https://github.com/danpros/htmly/releases/tag/v2.8.4

**Comment by oleteacher** [comment]
Thanks @bttrx! Totally missed that and it is wonderful news. The school IT department alerted us that they were removing all instances of HTMLY on Jan 4 because outdated. Now we can keep (I hope).

**Comment by danpros** [comment]
@lexavey I still safe and sound 😃 I will close this one. Thanks.

**Comment by anasfanani** [comment]
I've submit PR https://github.com/danpros/htmly/pull/663, please review
