### ISSUE TITLE
metatags

### ISSUE THREAD

**Issue by philips300-code** [danpros/htmly#741]
/admin/config/metatags

Posts: %post_title%
I removed %blog_title% .

At first there was no "-_simple_" in the search engine.
But the last 1-2 days the name of the site(_simple_) is also displayed

I have removed %blog_title% 

Can just the **title** stay.

![Без име](https://github.com/danpros/htmly/assets/57016132/6c45d286-561b-47e8-8648-070dd16782a1)

**Comment by danpros** [comment]
Hello,

Search engine (example: Google) is known to rewrite the title according to their algo. It could because the title is too short etc.

If we have deleted the blog title in the title and search engine decided to include the blog title then we could not do anything. You can get a more comprehensive answer if you ask it in the SEO forum.

**Comment by philips300-code** [comment]
> Hello,
> 
> Search engine (example: Google) is known to rewrite the title according to their algo. It could because the title is too short etc.
> 
> If we have deleted the blog title in the title and search engine decided to include the blog title then we could not do anything. You can get a more comprehensive answer if you ask it in the SEO forum.

Hello
thank you for the information.

Will there be a comments and voting section in the future?

**Comment by danpros** [comment]
At present there are no plans to add these features (built-in comments and voting), but can change in the future.

I will close this one because the main topic has been answered. Thanks.
